swagger: "2.0"
info:
  description: "This is the API specification of the server"
  version: "1.0.0"
  title: "pocAngularOfflineServer"
paths:
  "/hockey-players":
    get:
      tags:
      - "Hockey players"
      summary: "Get a list of hockey player"
      description: ""
      operationId: "getHockeyPlayers"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successfully retrieve hockey player list"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/HockeyPlayer"
        304:
          description: "Already have the more recent list. Caching purpose"
definitions:
  HockeyPlayer:
    type: "object"
    properties:
      id:
        type: "string"
        example: "564"
      firstname:
        type: "string"
        example: "Jean"
      lastname:
        type: "string"
        example: "Béliveau"